version: '2'

services:
  cat-db:
    image: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    networks:
      - demo

  cat-server:
   build: ./cat-server
   depends_on:
     - cat-db
   networks:
      - demo

  cat-server-app:
   build: ./cat-server-app
   depends_on:
     - cat-db
     - cat-server
   networks:
      - demo

networks:
  demo:
    driver: bridge